version: "3.9"  # optional since v1.27.0
services:
  web:
    build: .
    container_name: "api-user-jwt"
    command: "/bin/sh -c npm install &&"
    ports:
      - 3000:5000
    volumes:
      - .:/.